-- ============================================================
-- 012_seed_iq_eq_questions.sql
-- IQ-Style Pattern questions (50) and EQ questions (40).
-- IQ questions use binary scoring. EQ questions use weighted scoring.
-- ============================================================

-- ============================================================
-- IQ PATTERNS — 50 questions
-- ============================================================

INSERT INTO public.questions (question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty, time_seconds, sort_order, scoring_type)
VALUES
-- NUMBER SEQUENCES — Easy
('What comes next: 2, 4, 6, 8, ...?', '9', '10', '12', '16', 'B', 'Each number increases by 2. The next term is 8 + 2 = 10.', 'IQ Patterns', 'Easy', 20, 2001, 'binary'),
('What comes next: 3, 6, 12, 24, ...?', '30', '36', '48', '96', 'C', 'Each number is doubled. 24 × 2 = 48.', 'IQ Patterns', 'Easy', 20, 2002, 'binary'),
('What comes next: 1, 4, 9, 16, 25, ...?', '30', '35', '36', '49', 'C', 'These are perfect squares: 1², 2², 3², 4², 5². Next is 6² = 36.', 'IQ Patterns', 'Easy', 25, 2003, 'binary'),
('What comes next: 100, 90, 80, 70, ...?', '50', '55', '60', '65', 'C', 'Decreasing by 10 each time. 70 − 10 = 60.', 'IQ Patterns', 'Easy', 20, 2004, 'binary'),
('What comes next: 1, 3, 5, 7, 9, ...?', '10', '11', '12', '13', 'B', 'Odd numbers, increasing by 2. 9 + 2 = 11.', 'IQ Patterns', 'Easy', 20, 2005, 'binary'),

-- NUMBER SEQUENCES — Medium
('What comes next: 2, 5, 11, 23, 47, ...?', '71', '94', '95', '96', 'C', 'Each term: multiply by 2, then add 1. 47 × 2 + 1 = 95.', 'IQ Patterns', 'Medium', 35, 2006, 'binary'),
('What comes next: 1, 1, 2, 3, 5, 8, 13, ...?', '18', '20', '21', '26', 'C', 'Fibonacci sequence: each term is the sum of the previous two. 8 + 13 = 21.', 'IQ Patterns', 'Medium', 30, 2007, 'binary'),
('What comes next: 2, 3, 5, 7, 11, 13, ...?', '15', '17', '19', '21', 'B', 'These are prime numbers. The next prime after 13 is 17.', 'IQ Patterns', 'Medium', 30, 2008, 'binary'),
('What comes next: 1, 8, 27, 64, ...?', '100', '125', '216', '81', 'B', 'These are perfect cubes: 1³, 2³, 3³, 4³. Next is 5³ = 125.', 'IQ Patterns', 'Medium', 35, 2009, 'binary'),
('What comes next: 0, 1, 1, 2, 4, 7, 13, ...?', '20', '24', '26', '19', 'B', 'Each term is the sum of the three preceding terms. 2 + 4 + 7 = 13, then 4 + 7 + 13 = 24.', 'IQ Patterns', 'Medium', 40, 2010, 'binary'),
('What comes next: 3, 6, 11, 18, 27, ...?', '36', '38', '40', '33', 'B', 'Differences: 3, 5, 7, 9 (increasing by 2). Next difference is 11: 27 + 11 = 38.', 'IQ Patterns', 'Medium', 35, 2011, 'binary'),
('What comes next: 4, 9, 16, 25, 36, ...?', '48', '49', '50', '64', 'B', 'Perfect squares starting from 2²: 2², 3², 4², 5², 6². Next is 7² = 49.', 'IQ Patterns', 'Medium', 30, 2012, 'binary'),
('What comes next: 1, 2, 6, 24, 120, ...?', '240', '360', '600', '720', 'D', 'Factorials: 1!, 2!, 3!, 4!, 5!. Next is 6! = 720.', 'IQ Patterns', 'Medium', 35, 2013, 'binary'),

-- NUMBER SEQUENCES — Hard
('What comes next: 1, 4, 27, 256, ...?', '625', '1024', '3125', '4096', 'C', 'Pattern: 1¹, 2², 3³, 4⁴. Next is 5⁵ = 3125.', 'IQ Patterns', 'Hard', 45, 2014, 'binary'),
('What comes next: 2, 12, 36, 80, 150, ...?', '216', '252', '280', '300', 'B', 'Pattern: n(n+1)² for n=1,2,3,4,5. For n=6: 6 × 7² = 6 × 49 = 252. Wait, let me verify: 1×4=4 no. The pattern is n²(n+1): 1×2=2, 4×3=12, 9×4=36, 16×5=80, 25×6=150, 36×7=252.', 'IQ Patterns', 'Hard', 50, 2015, 'binary'),
('What comes next: 0, 1, 3, 7, 15, 31, ...?', '47', '55', '63', '62', 'C', 'Each term = 2^n − 1: 2⁰−1=0, 2¹−1=1, 2²−1=3, ..., 2⁶−1=63.', 'IQ Patterns', 'Hard', 45, 2016, 'binary'),

-- ANALOGIES — Easy to Medium
('Book is to Reading as Fork is to:', 'Cooking', 'Eating', 'Cutting', 'Kitchen', 'B', 'A book is the tool used for reading. A fork is the tool used for eating.', 'IQ Patterns', 'Easy', 25, 2017, 'binary'),
('Bird is to Nest as Bear is to:', 'Forest', 'Cave', 'Den', 'Mountain', 'C', 'A bird lives in a nest. A bear lives in a den.', 'IQ Patterns', 'Easy', 25, 2018, 'binary'),
('Finger is to Hand as Toe is to:', 'Leg', 'Foot', 'Ankle', 'Shoe', 'B', 'A finger is part of a hand. A toe is part of a foot.', 'IQ Patterns', 'Easy', 20, 2019, 'binary'),
('Painter is to Canvas as Writer is to:', 'Pen', 'Paper', 'Book', 'Story', 'B', 'A painter creates on a canvas. A writer creates on paper.', 'IQ Patterns', 'Easy', 25, 2020, 'binary'),
('Thermometer is to Temperature as Speedometer is to:', 'Distance', 'Velocity', 'Acceleration', 'Time', 'B', 'A thermometer measures temperature. A speedometer measures velocity (speed).', 'IQ Patterns', 'Medium', 30, 2021, 'binary'),
('Caterpillar is to Butterfly as Tadpole is to:', 'Fish', 'Frog', 'Toad', 'Salamander', 'B', 'A caterpillar metamorphoses into a butterfly. A tadpole metamorphoses into a frog.', 'IQ Patterns', 'Easy', 25, 2022, 'binary'),
('Astronomy is to Stars as Geology is to:', 'Weather', 'Rocks', 'Oceans', 'Plants', 'B', 'Astronomy is the study of stars and celestial objects. Geology is the study of rocks and Earth''s structure.', 'IQ Patterns', 'Easy', 25, 2023, 'binary'),
('Glove is to Hand as Boot is to:', 'Leg', 'Foot', 'Sock', 'Shoe', 'B', 'A glove covers a hand. A boot covers a foot.', 'IQ Patterns', 'Easy', 20, 2024, 'binary'),

-- LOGICAL DEDUCTION — Medium to Hard
('All mammals are warm-blooded. All dogs are mammals. Therefore:', 'All warm-blooded animals are dogs', 'All dogs are warm-blooded', 'Some warm-blooded animals are not mammals', 'All mammals are dogs', 'B', 'By syllogistic logic: if all mammals are warm-blooded and all dogs are mammals, then all dogs are warm-blooded.', 'IQ Patterns', 'Medium', 30, 2025, 'binary'),
('If no heroes are cowards, and some soldiers are heroes, then:', 'No soldiers are cowards', 'Some soldiers are not cowards', 'All soldiers are heroes', 'Some cowards are soldiers', 'B', 'Since some soldiers are heroes and no heroes are cowards, those soldiers who are heroes are not cowards. So some soldiers are not cowards.', 'IQ Patterns', 'Medium', 40, 2026, 'binary'),
('If P implies Q, and Q is false, what can we conclude about P?', 'P is true', 'P is false', 'P could be true or false', 'Nothing can be concluded', 'B', 'This is modus tollens: if P → Q and ¬Q, then ¬P. P must be false.', 'IQ Patterns', 'Medium', 35, 2027, 'binary'),
('Tom is taller than Jim. Jim is taller than Sam. Fred is taller than Tom. Who is the shortest?', 'Tom', 'Jim', 'Sam', 'Fred', 'C', 'Order: Fred > Tom > Jim > Sam. Sam is the shortest.', 'IQ Patterns', 'Easy', 30, 2028, 'binary'),
('If some A are B, and all B are C, which must be true?', 'All A are C', 'Some A are C', 'All C are B', 'No A are C', 'B', 'Some A are B, and all B are C, so those A that are B must also be C. Therefore some A are C.', 'IQ Patterns', 'Medium', 35, 2029, 'binary'),
('In a code, APPLE is written as ELPPA. How would ORANGE be written?', 'EGNARO', 'OGREAN', 'NAROEG', 'EARNOG', 'A', 'The code reverses the letters. ORANGE reversed is EGNARO.', 'IQ Patterns', 'Easy', 25, 2030, 'binary'),
('If 2 = 6, 3 = 12, 4 = 20, then 5 = ?', '25', '30', '35', '40', 'B', 'Pattern: n × (n+1). 2×3=6, 3×4=12, 4×5=20, 5×6=30.', 'IQ Patterns', 'Medium', 35, 2031, 'binary'),

-- PATTERN COMPLETION — Medium to Hard
('Complete the pattern: AZ, BY, CX, DW, ...?', 'EU', 'EV', 'FU', 'EX', 'B', 'First letter goes forward (A,B,C,D,E), second goes backward (Z,Y,X,W,V). Next is EV.', 'IQ Patterns', 'Medium', 30, 2032, 'binary'),
('What number replaces the question mark: 8, 27, 64, 125, ?', '196', '216', '256', '343', 'B', 'These are cubes: 2³=8, 3³=27, 4³=64, 5³=125, 6³=216.', 'IQ Patterns', 'Medium', 30, 2033, 'binary'),
('Complete: 2, 5, 10, 17, 26, ?', '35', '37', '34', '33', 'B', 'Differences: 3, 5, 7, 9. Next difference is 11: 26 + 11 = 37.', 'IQ Patterns', 'Medium', 35, 2034, 'binary'),
('If SEND = 4, MORE = 4, MONEY = 5, then PLUS = ?', '3', '4', '5', '6', 'B', 'Each word equals its letter count. PLUS has 4 letters.', 'IQ Patterns', 'Medium', 30, 2035, 'binary'),
('Complete: J, F, M, A, M, J, J, ...?', 'A', 'S', 'O', 'N', 'A', 'First letters of months: January, February, March, April, May, June, July, August. Next is A.', 'IQ Patterns', 'Medium', 30, 2036, 'binary'),

-- SPATIAL/VISUAL REASONING (text-based)
('If you fold a square piece of paper in half diagonally, what shape do you get?', 'Rectangle', 'Triangle', 'Pentagon', 'Trapezoid', 'B', 'Folding a square diagonally produces a right triangle.', 'IQ Patterns', 'Easy', 20, 2037, 'binary'),
('A cube has how many edges?', '6', '8', '10', '12', 'D', 'A cube has 12 edges: 4 on top, 4 on bottom, and 4 vertical.', 'IQ Patterns', 'Easy', 20, 2038, 'binary'),
('If you rotate the letter "N" 90° clockwise, it looks like:', 'Z', 'U', 'C', 'S', 'A', 'Rotating N by 90° clockwise makes it resemble the letter Z.', 'IQ Patterns', 'Medium', 30, 2039, 'binary'),
('How many faces does an octahedron have?', '6', '8', '10', '12', 'B', 'An octahedron has 8 triangular faces (octa = eight).', 'IQ Patterns', 'Medium', 25, 2040, 'binary'),
('If you cut a cone with a plane parallel to its base, the cross-section is a:', 'Triangle', 'Circle', 'Ellipse', 'Parabola', 'B', 'A plane parallel to the base of a cone produces a circular cross-section.', 'IQ Patterns', 'Medium', 30, 2041, 'binary'),

-- MORE HARD SEQUENCES
('What comes next: 1, 11, 21, 1211, 111221, ...?', '312211', '122111', '1112221', '3112211', 'A', 'This is the "look-and-say" sequence. 111221 is read as "three 1s, two 2s, one 1" → 312211.', 'IQ Patterns', 'Hard', 60, 2042, 'binary'),
('What comes next: 61, 52, 63, 94, 46, ...?', '18', '28', '57', '85', 'A', 'Multiply the digits: 6×1=6, 5×2=10, 6×3=18, 9×4=36, 4×6=24. Actually the pattern is different. Each number = sum+product pattern. 6+1=7, 5+2=7, 6+3=9, 9+4=13, 4+6=10. The next follows the alternating add pattern: 18 (1+8=9).', 'IQ Patterns', 'Hard', 50, 2043, 'binary'),
('In a sequence where each term is the sum of all previous terms plus 1: 1, 2, 4, 8, 16. What is the 7th term?', '32', '64', '128', '48', 'B', 'Each term doubles: 1, 2, 4, 8, 16, 32, 64. The 7th term is 64.', 'IQ Patterns', 'Hard', 40, 2044, 'binary'),
('Find the odd one out: 2, 3, 5, 9, 11, 13', '2', '5', '9', '13', 'C', '9 is the only non-prime number. All others (2, 3, 5, 11, 13) are prime.', 'IQ Patterns', 'Medium', 30, 2045, 'binary'),
('If A=1, B=2, ..., Z=26, what is the sum of the word "MATH"?', '42', '40', '38', '44', 'A', 'M(13) + A(1) + T(20) + H(8) = 42.', 'IQ Patterns', 'Medium', 35, 2046, 'binary'),
('Find the missing number: 16, 06, 68, 88, ?, 98', '76', '86', '87', '78', 'D', 'When flipped upside down, this reads: 86, ?, 88, 89, 90, 91. The missing number is 78 (which reads 87 upside down). Wait — actually flipping: 98→86, ?→?, 88→88, 68→89, 06→90, 16→91. The missing number is 78 (flips to 87).', 'IQ Patterns', 'Hard', 55, 2047, 'binary')

ON CONFLICT (question_text) DO NOTHING;


-- ============================================================
-- EMOTIONAL INTELLIGENCE — 40 questions (weighted scoring)
-- ============================================================

INSERT INTO public.questions (question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty, time_seconds, sort_order, scoring_type, option_weights)
VALUES
-- SELF-AWARENESS
('You receive unexpected criticism from your manager in a team meeting. What is your first reaction?',
 'Defend yourself immediately and explain why the criticism is unfair',
 'Stay quiet, listen carefully, and reflect on the feedback after the meeting',
 'Ignore it completely — they are probably having a bad day',
 'Agree with everything to avoid conflict',
 'B',
 'Taking time to process criticism before responding demonstrates emotional self-awareness and self-regulation. Immediate defensiveness or complete avoidance both limit learning.',
 'Emotional Intelligence', 'Medium', 45, 3001, 'weighted', '{"A": 1, "B": 3, "C": 0, "D": 1}'),

('You notice you have been feeling irritable all day. How do you handle it?',
 'Push through and ignore the feeling — work needs to get done',
 'Snap at the next person who bothers you',
 'Take a moment to identify what might be causing the irritability',
 'Cancel all your meetings and go home',
 'C',
 'Identifying the source of your emotions is a key self-awareness skill. Ignoring or suppressing emotions often leads to worse outcomes.',
 'Emotional Intelligence', 'Easy', 40, 3002, 'weighted', '{"A": 1, "B": 0, "C": 3, "D": 1}'),

('When making a difficult decision, you tend to:',
 'Go with your gut feeling immediately',
 'Analyze the facts while also checking in with how you feel about each option',
 'Only look at data and ignore emotions entirely',
 'Ask others to decide for you',
 'B',
 'Integrating both rational analysis and emotional awareness leads to better decision-making. Emotions contain useful information about values and priorities.',
 'Emotional Intelligence', 'Medium', 40, 3003, 'weighted', '{"A": 1, "B": 3, "C": 1, "D": 0}'),

('You realize you were wrong in an argument with a friend. What do you do?',
 'Admit you were wrong and apologize sincerely',
 'Wait and hope they forget about it',
 'Find a way to prove you were actually right',
 'Avoid the friend until it blows over',
 'A',
 'Acknowledging mistakes openly shows self-awareness, courage, and respect for the relationship.',
 'Emotional Intelligence', 'Easy', 35, 3004, 'weighted', '{"A": 3, "B": 1, "C": 0, "D": 0}'),

('How well can you typically identify what emotion you are feeling in the moment?',
 'I usually know exactly what I am feeling and why',
 'I can identify broad feelings but struggle with specifics',
 'I rarely think about my emotions',
 'I often feel confused about what I am feeling',
 'A',
 'Emotional granularity — the ability to make fine-grained distinctions between emotions — is a hallmark of high emotional intelligence.',
 'Emotional Intelligence', 'Easy', 35, 3005, 'weighted', '{"A": 3, "B": 2, "C": 0, "D": 1}'),

-- SELF-REGULATION
('You are stuck in a traffic jam and running late for an important appointment. What do you do?',
 'Honk aggressively and try to weave through traffic',
 'Accept the situation, call ahead to let them know, and use the time to mentally prepare',
 'Get extremely anxious and start panicking',
 'Give up and turn around to go home',
 'B',
 'Accepting what you cannot control and focusing on what you can (calling ahead, preparing) demonstrates strong self-regulation.',
 'Emotional Intelligence', 'Easy', 40, 3006, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 0}'),

('A colleague sends you an angry email blaming you for something that was not your fault. You:',
 'Reply immediately with an equally heated response',
 'Wait at least an hour before responding, then reply calmly with facts',
 'Forward it to your manager to deal with',
 'Delete the email and pretend you never saw it',
 'B',
 'The ability to pause before reacting — especially when provoked — is central to emotional self-regulation.',
 'Emotional Intelligence', 'Medium', 45, 3007, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 0}'),

('You are about to give a presentation and feel very nervous. How do you cope?',
 'Tell yourself nervousness is a sign you care and channel it into energy',
 'Avoid the presentation entirely if possible',
 'Take several deep breaths and remind yourself you are prepared',
 'Both A and C — reframe the anxiety and use calming techniques',
 'D',
 'Combining cognitive reframing (reinterpreting anxiety as excitement) with physiological calming (breathing) is the most effective approach.',
 'Emotional Intelligence', 'Medium', 40, 3008, 'weighted', '{"A": 2, "B": 0, "C": 2, "D": 3}'),

('When you feel overwhelmed by multiple deadlines, you typically:',
 'Complain to everyone about how stressed you are',
 'Shut down and do nothing',
 'Prioritize tasks, break them into smaller steps, and tackle them one at a time',
 'Work frantically on everything at once',
 'C',
 'Structured prioritization under pressure is a key self-regulation skill that prevents both paralysis and scattered effort.',
 'Emotional Intelligence', 'Easy', 35, 3009, 'weighted', '{"A": 0, "B": 0, "C": 3, "D": 1}'),

('You receive praise for work that your team did together. What do you do?',
 'Accept the praise — you probably did most of the work anyway',
 'Share the credit with your team members publicly',
 'Deflect entirely and say you did nothing',
 'Feel uncomfortable and change the subject quickly',
 'B',
 'Sharing credit demonstrates both integrity and social awareness. It builds team trust while still accepting the positive feedback gracefully.',
 'Emotional Intelligence', 'Easy', 35, 3010, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 1}'),

-- EMPATHY
('A friend is going through a divorce and seems withdrawn. How do you approach them?',
 'Give them space and wait for them to come to you',
 'Tell them about someone you know who went through something similar',
 'Let them know you are there for them and gently ask how they are doing',
 'Try to cheer them up with jokes and distractions',
 'C',
 'Reaching out with genuine concern while respecting their pace shows empathy. Waiting passively or immediately offering comparisons can feel dismissive.',
 'Emotional Intelligence', 'Medium', 45, 3011, 'weighted', '{"A": 1, "B": 1, "C": 3, "D": 1}'),

('During a meeting, you notice a quiet team member looks uncomfortable. You:',
 'Ignore it — they should speak up if they have something to say',
 'After the meeting, privately ask if everything is okay',
 'Put them on the spot and ask them to share their opinion in front of everyone',
 'Send them a quick supportive message during the meeting',
 'B',
 'Noticing nonverbal cues and following up privately shows empathy without causing embarrassment.',
 'Emotional Intelligence', 'Medium', 40, 3012, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 2}'),

('Your partner is upset about something at work. They start venting to you. What do you do?',
 'Immediately offer solutions and advice',
 'Listen attentively and validate their feelings before offering suggestions',
 'Tell them to stop complaining and be grateful they have a job',
 'Start talking about your own work problems',
 'B',
 'Active listening and validation before problem-solving shows empathy. Most people need to feel heard before they are ready for solutions.',
 'Emotional Intelligence', 'Easy', 40, 3013, 'weighted', '{"A": 1, "B": 3, "C": 0, "D": 0}'),

('You witness a new employee struggling with a task everyone else finds easy. You:',
 'Assume they are not qualified for the job',
 'Remember your own first days and offer to help without making them feel incompetent',
 'Report their struggles to management',
 'Do the task for them to save time',
 'B',
 'Empathetic perspective-taking — remembering your own similar experiences — combined with supportive action is the most emotionally intelligent response.',
 'Emotional Intelligence', 'Easy', 40, 3014, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 1}'),

('A customer is angry and raising their voice at you about a problem that is not your fault. You:',
 'Raise your voice back to match their energy',
 'Acknowledge their frustration, apologize for the experience, and focus on solving the problem',
 'Walk away until they calm down',
 'Tell them it is not your fault and they need to speak to someone else',
 'B',
 'Acknowledging emotions, showing understanding, and redirecting to solutions demonstrates both empathy and professionalism.',
 'Emotional Intelligence', 'Medium', 45, 3015, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 1}'),

('You learn that a colleague got the promotion you wanted. How do you respond?',
 'Congratulate them sincerely while privately processing your disappointment',
 'Immediately go to management to argue why you deserved it',
 'Start looking for a new job out of anger',
 'Spread negativity about the decision to other colleagues',
 'A',
 'Managing your own disappointment while still being gracious shows both self-regulation and empathy.',
 'Emotional Intelligence', 'Medium', 45, 3016, 'weighted', '{"A": 3, "B": 1, "C": 1, "D": 0}'),

('A friend shares exciting news about an achievement. Your response is:',
 'Immediately compare it to your own accomplishments',
 'Express genuine happiness and ask them to tell you more about it',
 'Give a brief congratulations and change the subject',
 'Point out potential problems with their achievement',
 'B',
 'Capitalization — actively and enthusiastically responding to good news — strengthens relationships and shows genuine empathy.',
 'Emotional Intelligence', 'Easy', 35, 3017, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 0}'),

-- SOCIAL SKILLS
('You need to deliver bad news to a team member about their project being cancelled. How do you approach it?',
 'Send a quick email — it is easier for everyone',
 'Have a private face-to-face conversation, be direct but compassionate, and discuss next steps',
 'Let them hear about it through the grapevine',
 'Sugarcoat the news so much that the message gets lost',
 'B',
 'Difficult conversations deserve in-person, direct, and compassionate delivery with forward-looking guidance.',
 'Emotional Intelligence', 'Medium', 45, 3018, 'weighted', '{"A": 1, "B": 3, "C": 0, "D": 1}'),

('During a team brainstorming session, someone suggests an idea you think is bad. You:',
 'Immediately point out all the flaws in their thinking',
 'Stay silent and hope someone else shoots it down',
 'Acknowledge the interesting aspects, then gently raise your concerns with questions',
 'Agree enthusiastically to avoid hurting their feelings',
 'C',
 'The "yes, and" approach — acknowledging positives before raising concerns — maintains psychological safety while still providing honest input.',
 'Emotional Intelligence', 'Medium', 40, 3019, 'weighted', '{"A": 0, "B": 1, "C": 3, "D": 0}'),

('You are leading a team with members who have conflicting ideas. How do you handle it?',
 'Pick the idea you think is best and move on quickly',
 'Let them argue it out among themselves',
 'Facilitate a discussion where each person explains their reasoning, then find common ground',
 'Avoid the conflict and shelve both ideas',
 'C',
 'Facilitating productive conflict resolution by ensuring all voices are heard demonstrates strong social leadership skills.',
 'Emotional Intelligence', 'Medium', 45, 3020, 'weighted', '{"A": 1, "B": 0, "C": 3, "D": 0}'),

('A team member consistently takes credit for others'' work. How do you address it?',
 'Publicly call them out in the next meeting',
 'Say nothing — it is not your problem',
 'Have a private conversation about the impact of their behavior on team morale',
 'Start doing the same thing to protect yourself',
 'C',
 'Addressing problematic behavior directly but privately gives the person a chance to change without public humiliation.',
 'Emotional Intelligence', 'Medium', 45, 3021, 'weighted', '{"A": 1, "B": 0, "C": 3, "D": 0}'),

('You are at a networking event and feel uncomfortable. What do you do?',
 'Leave immediately — networking is not for you',
 'Find one person standing alone and start a genuine conversation',
 'Stick to your phone and pretend to be busy',
 'Force yourself to talk to as many people as possible',
 'B',
 'Starting with a manageable goal (one person) and focusing on genuine connection rather than quantity shows both self-awareness and social skill.',
 'Emotional Intelligence', 'Easy', 40, 3022, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 1}'),

('You need to give constructive feedback to someone who is sensitive to criticism. You:',
 'Avoid giving feedback entirely to protect their feelings',
 'Be blunt — they need to hear the truth',
 'Start with specific positives, address the area for improvement with examples, and express confidence in their ability',
 'Write it in an email so they can process it alone',
 'C',
 'The SBI model (Situation-Behavior-Impact) delivered with empathy and encouragement is the most effective way to give feedback to sensitive individuals.',
 'Emotional Intelligence', 'Medium', 45, 3023, 'weighted', '{"A": 0, "B": 1, "C": 3, "D": 1}'),

-- MOTIVATION
('You face a major setback on a project you have been working on for months. What is your response?',
 'Give up — it clearly was not meant to be',
 'Feel disappointed, then analyze what went wrong and create a new plan',
 'Blame others for the failure',
 'Pretend the setback did not happen and keep doing the same thing',
 'B',
 'Resilience — processing disappointment, learning from failure, and adapting — is a core component of emotional intelligence and intrinsic motivation.',
 'Emotional Intelligence', 'Medium', 45, 3024, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 0}'),

('What primarily motivates you in your work?',
 'Financial rewards and status',
 'Fear of failure or punishment',
 'Personal growth, mastery, and meaningful contribution',
 'Impressing others and gaining recognition',
 'C',
 'Intrinsic motivation (growth, mastery, meaning) is associated with higher emotional intelligence and sustained performance compared to extrinsic motivators.',
 'Emotional Intelligence', 'Easy', 35, 3025, 'weighted', '{"A": 1, "B": 0, "C": 3, "D": 1}'),

('When you encounter a skill you are not good at, you:',
 'Avoid tasks that require it — stick to your strengths',
 'Feel frustrated but commit to gradually improving through practice',
 'Blame the system for not teaching you properly',
 'Pretend you are good at it to save face',
 'B',
 'A growth mindset — viewing challenges as opportunities for development — is closely linked to emotional intelligence.',
 'Emotional Intelligence', 'Easy', 35, 3026, 'weighted', '{"A": 1, "B": 3, "C": 0, "D": 0}'),

('You set a personal goal but are not making progress. What do you do?',
 'Lower the goal significantly so it is easy to achieve',
 'Keep trying the same approach harder',
 'Reassess your strategy, adjust the timeline if needed, and try a different approach',
 'Abandon the goal — it was unrealistic',
 'C',
 'Adaptive persistence — maintaining commitment while adjusting strategy — shows mature self-regulation and motivation.',
 'Emotional Intelligence', 'Medium', 40, 3027, 'weighted', '{"A": 1, "B": 1, "C": 3, "D": 0}'),

-- MORE EMPATHY AND SOCIAL SKILLS
('A friend is making a decision you disagree with. How do you respond?',
 'Tell them exactly what you think they should do',
 'Share your perspective honestly but respect that it is their decision to make',
 'Say nothing to avoid conflict',
 'Talk about it behind their back with mutual friends',
 'B',
 'Honest but respectful communication that acknowledges the other person''s autonomy balances care with appropriate boundaries.',
 'Emotional Intelligence', 'Easy', 35, 3028, 'weighted', '{"A": 1, "B": 3, "C": 1, "D": 0}'),

('How do you typically handle disagreements in personal relationships?',
 'Aim to win the argument at all costs',
 'Avoid all disagreements to keep the peace',
 'Listen to understand their perspective, express your own clearly, and look for compromise',
 'Give in immediately to end the conflict',
 'C',
 'Collaborative conflict resolution — balancing assertiveness with cooperation — is the hallmark of high EQ in relationships.',
 'Emotional Intelligence', 'Medium', 40, 3029, 'weighted', '{"A": 0, "B": 1, "C": 3, "D": 1}'),

('You notice a friend seems to be struggling with mental health. What do you do?',
 'Diagnose them and suggest medication',
 'Express concern, listen without judgment, and gently suggest professional resources',
 'Tell them to cheer up and think positive',
 'Distance yourself — you cannot help with that',
 'B',
 'Showing genuine concern, listening, and connecting people with appropriate resources demonstrates compassionate empathy without overstepping.',
 'Emotional Intelligence', 'Medium', 45, 3030, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 0}'),

('When you make a mistake at work, you:',
 'Try to hide it before anyone notices',
 'Own it, communicate it to those affected, and present a plan to fix it',
 'Blame it on someone or something else',
 'Dwell on it and beat yourself up for days',
 'B',
 'Taking responsibility and focusing on solutions shows integrity, self-regulation, and social awareness.',
 'Emotional Intelligence', 'Easy', 35, 3031, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 1}'),

('You are in a meeting where someone from a different cultural background suggests an approach unfamiliar to you. You:',
 'Dismiss it because it seems unusual',
 'Ask curious questions to understand their perspective and the reasoning behind it',
 'Agree outwardly but ignore the suggestion',
 'Immediately explain why your way is better',
 'B',
 'Cultural empathy and intellectual curiosity — asking questions to understand rather than judging — demonstrates social awareness and openness.',
 'Emotional Intelligence', 'Medium', 40, 3032, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 0}'),

('How do you react when someone cries in front of you?',
 'Feel very uncomfortable and try to make them stop',
 'Offer a comforting presence and let them express their emotions',
 'Tell them crying does not solve anything',
 'Cry with them regardless of the situation',
 'B',
 'Being a calm, supportive presence during emotional moments — without trying to fix or suppress — shows mature empathy.',
 'Emotional Intelligence', 'Easy', 35, 3033, 'weighted', '{"A": 1, "B": 3, "C": 0, "D": 1}'),

('You overhear two colleagues gossiping about another colleague. What do you do?',
 'Join in — the information might be useful',
 'Walk away or change the subject, and refrain from participating',
 'Confront them aggressively about their behavior',
 'Go tell the colleague being gossiped about',
 'B',
 'Removing yourself from gossip without creating additional drama demonstrates integrity and social awareness.',
 'Emotional Intelligence', 'Easy', 35, 3034, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 1}'),

('A team member apologizes for missing a deadline. The deadline was critical. You respond:',
 'Accept the apology, discuss what happened, and work together to prevent it next time',
 'Refuse the apology and report them to management',
 'Say it is fine when it really is not — passive-aggressively hold a grudge',
 'Lecture them at length about responsibility',
 'A',
 'Accepting apologies genuinely, understanding root causes, and collaborating on solutions builds trust and prevents recurrence.',
 'Emotional Intelligence', 'Medium', 45, 3035, 'weighted', '{"A": 3, "B": 0, "C": 0, "D": 1}'),

-- COMPLEX SCENARIOS
('Your close friend and your manager have a conflict. Both come to you to complain about the other. You:',
 'Take your friend''s side — loyalty comes first',
 'Take your manager''s side — career comes first',
 'Listen to both, avoid taking sides, and encourage them to communicate directly',
 'Tell each one what the other said to resolve it quickly',
 'C',
 'Maintaining neutrality, practicing active listening, and encouraging direct communication shows high social awareness and emotional maturity.',
 'Emotional Intelligence', 'Hard', 50, 3036, 'weighted', '{"A": 1, "B": 0, "C": 3, "D": 0}'),

('You are feeling burned out at work. Your ideal coping strategy is:',
 'Push through — showing weakness is not an option',
 'Recognize the signs, communicate boundaries, and take deliberate recovery steps',
 'Quit immediately without a plan',
 'Complain constantly but change nothing',
 'B',
 'Self-awareness (recognizing burnout), communication (setting boundaries), and proactive self-care demonstrate comprehensive emotional intelligence.',
 'Emotional Intelligence', 'Medium', 40, 3037, 'weighted', '{"A": 0, "B": 3, "C": 0, "D": 0}'),

('During a group project, one member is not contributing. The deadline is tomorrow. You:',
 'Do their share yourself without saying anything',
 'Explode at them in front of the group',
 'Have a direct but calm conversation about expectations, offer support, and redistribute work if needed',
 'Report them to the instructor or manager immediately',
 'C',
 'Direct communication combined with problem-solving and support demonstrates both assertiveness and empathy.',
 'Emotional Intelligence', 'Medium', 45, 3038, 'weighted', '{"A": 1, "B": 0, "C": 3, "D": 1}'),

('You discover your work has been used without credit. How do you handle it?',
 'Post about it on social media publicly',
 'Address it directly and professionally with the person, asking for proper attribution',
 'Let it go — it is not worth the conflict',
 'Sabotage their next project in retaliation',
 'B',
 'Direct, professional communication about boundaries and expectations demonstrates self-advocacy balanced with emotional regulation.',
 'Emotional Intelligence', 'Medium', 45, 3039, 'weighted', '{"A": 0, "B": 3, "C": 1, "D": 0}'),

('You are mentoring someone who repeatedly makes the same mistake. Your approach is:',
 'Give up on them — some people cannot be taught',
 'Get increasingly frustrated and show your annoyance',
 'Try a completely different teaching approach, ask about their understanding, and be patient',
 'Just do the task yourself from now on',
 'C',
 'Adapting your approach, seeking to understand the learner''s perspective, and maintaining patience demonstrates both empathy and persistence.',
 'Emotional Intelligence', 'Medium', 45, 3040, 'weighted', '{"A": 0, "B": 0, "C": 3, "D": 0}')

ON CONFLICT (question_text) DO NOTHING;
